{
  pkgs,
  inputs,
  lib,
  ...
}:
{
  imports = [
    inputs.dms.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms-plugin-registry.modules.default
    ./niri.nix
    ./apptheme
  ];
  systemd.user.services.niri-flake-polkit = lib.mkForce {
    enable = false;
  }; # Disable niri-flake's default polkit agent to avoid conflicts
  programs.dank-material-shell = {
    enable = true;
    # quickshell.package = inputs.quickshell.packages.${pkgs.hostPlatform.system}.default;

    systemd = {
      enable = true;
      restartIfChanged = true;
    };

    # Core features
    enableSystemMonitoring = true; # System monitoring widgets (dgop)
    enableVPN = true; # VPN management widget
    enableDynamicTheming = true; # Wallpaper-based theming (matugen)
    enableAudioWavelength = true; # Audio visualizer (cava)
    enableCalendarEvents = true; # Calendar integration (khal)
    enableClipboardPaste = true; # Pasting items from the clipboard (wtype)

    niri = {
      # enableKeybinds = true; # Sets static preset keybinds
      # enableSpawn = true; # Auto-start DMS with niri, if enabled
      includes = {
        enable = true; # Enable config includes hack. Enabled by default.

        override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        originalFileName = "niri-flake"; # A new name (without extension) for the config file generated by niri-flake.
        filesToInclude = [
          # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
          "alttab" # Please note that niri will throw an error if any of these files are missing.
          "binds"
          "colors"
          "cursor"
          "layout"
          "outputs"
          "windowrules"
          "wpblur"
        ];
      };
    };
    settings = import ./settings.nix;
    session = import ./session.nix;
    clipboardSettings = {
      maxHistory = 25;
      maxEntrySize = 5242880;
      autoClearDays = 1;
      clearAtStartup = true;
      disabled = false;
      disableHistory = false;
      disablePersist = true;
    };
    # Auto-enabled when plugins have settings configured
    managePluginSettings = true;
    plugins = {
      dankKDEConnect = {
        enable = true;
      };
      dankGifSearch = {
        enable = true;
      };
      dankLauncherKeys = {
        enable = true;
      };
      dankStickerSearch = {
        enable = true;
      };
      # somePlugin = {
      #   enable = true;
      #   settings = {
      #     # Your plugin settings here
      #   };
      # };
    };
  };
}
